/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../common.js"
  import type { Counter, CounterInterface } from "../Counter.js";

  const _abi = [
  {
    "inputs": [],
    "name": "count",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "decrement",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "increment",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  const _bytecode = "0x6080604052348015600e575f5ffd5b506102638061001c5f395ff3fe608060405234801561000f575f5ffd5b506004361061003f575f3560e01c806306661abd146100435780632baeceb714610061578063d09de08a1461006b575b5f5ffd5b61004b610075565b6040516100589190610109565b60405180910390f35b61006961007a565b005b6100736100d7565b005b5f5481565b5f5f54116100bd576040517f08c379a00000000000000000000000000000000000000000000000000000000081526004016100b49061017c565b60405180910390fd5b60015f5f8282546100ce91906101c7565b92505081905550565b60015f5f8282546100e891906101fa565b92505081905550565b5f819050919050565b610103816100f1565b82525050565b5f60208201905061011c5f8301846100fa565b92915050565b5f82825260208201905092915050565b7f42656c6f77207a65726f000000000000000000000000000000000000000000005f82015250565b5f610166600a83610122565b915061017182610132565b602082019050919050565b5f6020820190508181035f8301526101938161015a565b9050919050565b7f4e487b71000000000000000000000000000000000000000000000000000000005f52601160045260245ffd5b5f6101d1826100f1565b91506101dc836100f1565b92508282039050818111156101f4576101f361019a565b5b92915050565b5f610204826100f1565b915061020f836100f1565b92508282019050808211156102275761022661019a565b5b9291505056fea26469706673582212209b9ed3932054303587819655faae3ca43bb0084669bca5c9718b40c650bca61664736f6c634300081c0033";

  
      type CounterConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: CounterConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class Counter__factory extends ContractFactory {
    
      constructor(...args: CounterConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(overrides || {});
    };
    override deploy(overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(overrides || {}) as Promise<Counter & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): Counter__factory {
      return super.connect(runner) as Counter__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): CounterInterface {
      return new Interface(_abi) as CounterInterface;
    }
    
    override attach(address: string | Addressable): Counter {
      return super.attach(address) as Counter;
    }
  static connect(address: string, runner?: ContractRunner | null): Counter {
      return new Contract(address, _abi, runner) as unknown as Counter;
    }
  }

  
  